apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: ingress-gateways
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dummy.invalid
  namespace: ingress-gateways
spec:
  dnsNames:
    - dummy.invalid
  secretName: dummy.invalid
  issuerRef:
    name: test-selfsigned
