apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: ingress-gateways
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: non-existing-smotra-net-cert
  namespace: ingress-gateways
spec:
  dnsNames:
    - non-existing.smotra.net
  secretName: non-existing-smotra-net-cert-tls
  issuerRef:
    name: test-selfsigned
